export const therapistsData = [
  {
    name: "Emily Johnson",
    age: 42,
    email: "emily.johnson@example.com",
    experience: "15 years",
    cost: "$120/session",
  },
  {
    name: "Michael Thompson",
    age: 52,
    email: "michael.thompson@example.com",
    experience: "20 years",
    cost: "$150/session",
  },
  {
    name: "Sarah Wilson",
    age: 36,
    email: "sarah.wilson@example.com",
    experience: "8 years",
    cost: "$100/session",
  },
  {
    name: "David Anderson",
    age: 47,
    email: "david.anderson@example.com",
    experience: "18 years",
    cost: "$140/session",
  },
  {
    name: "Jessica Taylor",
    age: 39,
    email: "jessica.taylor@example.com",
    experience: "12 years",
    cost: "$125/session",
  },
  {
    name: "Robert Clark",
    age: 55,
    email: "robert.clark@example.com",
    experience: "22 years",
    cost: "$160/session",
  },
  {
    name: "Olivia Lewis",
    age: 31,
    email: "olivia.lewis@example.com",
    experience: "6 years",
    cost: "$90/session",
  },
  {
    name: "William Harris",
    age: 48,
    email: "william.harris@example.com",
    experience: "16 years",
    cost: "$135/session",
  },
  {
    name: "Sophia Thompson",
    age: 44,
    email: "sophia.thompson@example.com",
    experience: "14 years",
    cost: "$130/session",
  },
  {
    name: "James Wilson",
    age: 37,
    email: "james.wilson@example.com",
    experience: "9 years",
    cost: "$105/session",
  },
  {
    name: "Ava Clark",
    age: 29,
    email: "ava.clark@example.com",
    experience: "4 years",
    cost: "$85/session",
  },
  {
    name: "Benjamin Rodriguez",
    age: 51,
    email: "benjamin.rodriguez@example.com",
    experience: "19 years",
    cost: "$145/session",
  },
  {
    name: "Mia Anderson",
    age: 33,
    email: "mia.anderson@example.com",
    experience: "7 years",
    cost: "$95/session",
  },
  {
    name: "Daniel Martinez",
    age: 46,
    email: "daniel.martinez@example.com",
    experience: "17 years",
    cost: "$135/session",
  },
  {
    name: "Isabella Taylor",
    age: 41,
    email: "isabella.taylor@example.com",
    experience: "13 years",
    cost: "$125/session",
  },
  {
    name: "Matthew Hernandez",
    age: 38,
    email: "matthew.hernandez@example.com",
    experience: "10 years",
    cost: "$110/session",
  },
  {
    name: "Emma Gonzalez",
    age: 35,
    email: "emma.gonzalez@example.com",
    experience: "8 years",
    cost: "$100/session",
  },
  {
    name: "Alexander Perez",
    age: 54,
    email: "alexander.perez@example.com",
    experience: "21 years",
    cost: "$155/session",
  },
  {
    name: "Abigail Sanchez",
    age: 30,
    email: "abigail.sanchez@example.com",
    experience: "5 years",
    cost: "$90/session",
  },
  {
    name: "Jacob Ramirez",
    age: 49,
    email: "jacob.ramirez@example.com",
    experience: "18 years",
    cost: "$140/session",
  },
];
