POST http://localhost:3000/api/post
Content-Type: application/json

{
  "userId": "66272df730505d49be4eb6cd",
  "content": "This is a test post",
}

###

GET http://localhost:3000/api/post

###

PATCH http://localhost:3000/api/post
Content-Type: application/json

{
  "commentId": "66276c9ad9515c7198e25d3e",
  "postId": "66275de7d9515c7198e25cd4",
  "authorName": "Airudh Varma"
}

###

GET http://localhost:3000/api/post/662742b130505d49be4eb75a