POST http://localhost:3000/api/post
Content-Type: application/json

{
  "uid": "W4ElMP4RhMfug4uzSgSRmbAuIv92",
  "content": "This is a test post"
}

###

GET http://localhost:3000/api/post

###

PATCH http://localhost:3000/api/post
Content-Type: application/json

{
  "commentId": "6626bb047bc53ad33abaf15a",
  "postId": "6626bb0c7bc53ad33abaf15c"
}

###

GET http://localhost:3000/api/post/6626bb047bc53ad33abaf15a